version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: /home/Front-end-2/Dockerfile
    ports:
      - "3000:7000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped
